services:
  - type: web
    name: cineflix-full
    env: node
    plan: free
    repo: <YOUR_GIT_REPO_URL>
    branch: main
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://<user>:<pass>@cluster0.mongodb.net/cineflix?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: change_this_secret
